---
- hosts: all
  remote_user: ubuntu
  become: yes
  vars:
    password: nope

  tasks:
    - user: name=lorebot state=present groups=primary-group groups="sudo"
    - sudo: yes
    - name: Set lorebot's authorized key
      authorized_key:
        user: lorebot
        state: present
        key: "{{ lookup('file', '/home/malcolm/Projects/service-management/lorebot.pub') }}"
