---
- hosts: all
  remote_user: lorebot
  tasks:
  - name: Clone repo
    git:
      repo: 'git@github.com:mbc1990/lore.git'
      version: master
      dest: /home/lorebot/lorebot
      accept_hostkey: true
  - name: Get psql dep
    environment:
      GOPATH: /home/lorebot/go
    command: /usr/local/go/bin/go get github.com/lib/pq
  - name: Get slack dep
    environment:
      GOPATH: /home/lorebot/go
    command: /usr/local/go/bin/go get github.com/nlopes/slack
  - name: Compile lorebot
    environment:
      GOPATH: /home/lorebot/go
    command: /usr/local/go/bin/go build
    args:
      chdir: /home/lorebot/lorebot/
