---
- hosts: all
  remote_user: lorebot
  tasks:
  - name: Clone repo
    git:
      repo: 'git@github.com:mbc1990/lore.git'
      version: master
      dest: /home/lorebot/lorebot
      accept_hostkey: true
