---
- hosts: all
  remote_user: ubuntu
  become: yes
  roles:
  - role: sansible.golang  # install go for lorebot
    sansible_golang_workspace_user: lorebot
    sansible_golang_tarball: go1.11.linux-amd64.tar.gz
    sansible_golang_tarball_checksum: b3fcf280ff86558e0559e185b601c9eade0fd24c900b4c63cd14d1d38613e499
  tasks:
  - name: Install list of packages
    apt: name={{item}} state=installed
    with_items:
         - git
         - htop
