---
- hosts: all
  remote_user: ubuntu
  become: yes
  roles:
  - role: sansible.golang  # install go for lorebot
    sansible_golang_workspace_user: lorebot
  tasks:
  - name: Install list of packages
    apt: name={{item}} state=installed
    with_items:
         - git
         - htop
